version: '3' # docker-composeの使用バージョン
services:    # 「作られるサービスの設定を以下に記載します」の意味
  nginx:     # コンテナネーム(注1)
    build: ./docker  # Dockerfileの場所
    ports:
      - "8080:80"  # EC2が公開しているポート番号:コンテナのポート番号
    volumes:
      - ./docs:/usr/share/nginx/html
