version: '3' # docker-composeの使用バージョン
services:    # 「作られるサービスの設定を以下に記載します」の意味
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: >-
        yourhostdomain.com -> http://nginx:80,
        0.0.0.0 -> http://nginx:80
      STAGE: local
    volumes:
      - ./ssl-certs:/var/lib/https-portal
  nginx:     # コンテナネーム(注1)
    build: ./docker  # Dockerfileの場所
    ports:
      - "8080:80"  # EC2が公開しているポート番号:コンテナのポート番号
    volumes:
      - ./docs:/usr/share/nginx/html
